# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'FunWithSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'

  target 'FunWithSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FunWithSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
